# Generated by Django 3.0 on 2022-06-02 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('std_class', models.PositiveIntegerField(null=True)),
                ('roll', models.PositiveIntegerField(null=True)),
                ('mark', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
